version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: correcta_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: correcta
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: correcta_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: correcta_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: correcta_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json

volumes:
  postgres_data_v2:
  redis_data:
  minio_data:
